#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 6003
spring:
  profiles: dev
  application:
    name: jingshuo-config-eureka
eureka:
  instance:
    hostname: eureka03.com # eureka服务端的实例名称
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka01.com:6001/eureka,http://eureka02.com:6002/eureka
    server:
      enable-self-preservation: false # 禁用自我保护机制*****************
---
server:
  port: 6003
spring:
  profiles: prod
  application:
    name: jingshuo-config-eureka
eureka:
  instance:
    hostname: eureka03.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka01.com:6001/eureka,http://eureka02.com:6002/eureka
    server:
      enable-self-preservation: true # 开启自我保护机制*****************
#保存时注意，选择 UTF-8 保存
