#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8003
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.jingshuo.uc.config.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: jingshuo-uc-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jdbc?serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
     defaultZone: http://eureka01.com:6001/eureka,http://eureka02.com:6002/eureka,http://eureka03.com:6003/eureka
#  这个版本已经是显示ip地址而不是主机名了
#  instance:
#    prefer-ip-address: true # 开启IP和地址的映射，页面上就显示ip地址
#    instance-id: ${spring.application.name}:${server.port} # 把显示信息设置为服务名加端口号

---
server:
  port: 8003
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.jingshuo.uc.config.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: prod
  application:
    name: jingshuo-uc-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jdbc?serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
     defaultZone: http://eureka01.com:6001/eureka,http://eureka02.com:6002/eureka,http://eureka03.com:6003/eureka
#  这个版本已经是显示ip地址而不是主机名了
#  instance:
#    prefer-ip-address: true # 开启IP和地址的映射，页面上就显示ip地址
#    instance-id: ${spring.application.name}:${server.port} # 把显示信息设置为服务名加端口号
